# .github/workflows/compile-pr.yml
name: Compile PR in Container

on:
  pull_request:
    branches: [main]  # Or your target branch

jobs:
  get_tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_sha.outputs.tag }}
    steps:
      - name: Get latest SHA from scarab-infra
        id: get_sha
        run: |
          LATEST_SHA=$(curl -s https://api.github.com/repos/litz-lab/scarab-infra/commits/main | jq -r '.sha')
          SHORT_SHA=$(echo "$LATEST_SHA" | cut -c1-7)
          echo "tag=$SHORT_SHA" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: get_tag
    container:
      image: ghcr.io/litz-lab/scarab-infra/allbench_traces:${{ needs.get_tag.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Mark Git repo as safe
        run: git config --global --add safe.directory /__w/scarab_ll/scarab_ll

      - name: Build Scarab Opt
        working-directory: src
        run: make opt -j

      - name: Build Scarab Dbg
        working-directory: src
        run: make dbg -j

      - name: Upload Scarab binary
        uses: actions/upload-artifact@v4
        with:
          name: scarab-binary
          path: src/scarab

  run-scarab:
    runs-on: ubuntu-latest
    needs: build  # can also depend on build if needed
    steps:
      #- name: Set up SSH for private repo access
      #  run: |
      #    mkdir -p ~/.ssh
      #    echo "${{ secrets.SCARAB_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      #    chmod 600 ~/.ssh/id_rsa
      #    ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone scarab-infra repo via SSH
        run: git clone https://github.com/litz-lab/scarab-infra.git
        #git clone git@github.com:litz-lab/scarab-infra.git

      #- name: Docker login to GHCR
      #  run: |
      #    echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Pull Scarab Docker image
        run: docker pull ghcr.io/litz-lab/scarab-infra/allbench_traces:${{ needs.get_tag.outputs.tag }}

      - name: Run Scarab simulation
        working-directory: scarab-infra
        run: |
          curl -L -o traces_top_simpoint.tar.gz https://github.com/litz-lab/scarab-infra/releases/download/top_simpoint_perlbench/traces_top_simpoint.tar.gz
          tar -xzf traces_top_simpoint.tar.gz
          chmod +x run.sh
          ./run.sh --simulation ./top_simpoint.json
