name: Sync Private Repo to Public

on:
  push:
    branches:
      - main            # Trigger when PR is merged into main
    workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Private Repository
        uses: actions/checkout@v4
        with:
          repository: litz-lab/scarab_ll
          fetch-depth: 0  # Full history for proper sync

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Public Repository Remote
        run: |
          git remote add public git@github.com:litz-lab/scarab.git
          git fetch public

      - name: Rebase Private Repo with Public Repo
        run: |
          git rebase public/main  # Rebase with the main branch of the public repo

      - name: Remove Sync Workflow for Public Repo
        run: |
          rm -f .github/workflows/sync-scarabs_workflow.yml

      - name: Push Updates to Public Repository
        env:
          DATE: ${{ github.event.head_commit.timestamp }}
        run: |
          DATE=$(date +%Y-%m-%d)  # Format date as YYYY-MM-DD
          git push public main:release_${DATE}  # Push to release_<date> branch
