name: Sync to Private Repo with Original Authors

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for proper sync

      - name: Configure Git (Kepp Original Authors)
        run: |
          git config --global user.email "$(git log -1 --pretty=format:'%ae')"
          git config --global user.name "$(git log -1 --pretty=format:'%an')"

      - name: Add Private Repository Remote
        run: |
          git remote add private https://github.com/litz-lab/scarab_ll.git
          git fetch private

      - name: Rebase Public Repo with Private Repo
        run: |
          git pull --rebase private main || git rebase --abort # Rebase with the main branch of the private repo

      - name: Remove Sync Workflow  # Each sync workflow of two repositories should differ
        run: |
          rm -f .github/workflows/sync-scarab-repos.yml

      - name: Push Updates to Private Repository
        if: github.event_name == 'push' # Only push on merge to main
        env:
          DATE: ${{ github.event.head_commit.timestamp }}
        run: |
          DATE=$(date +%Y-%m-%d)  # Format date as YYYY-MM-DD
          git push --force-with-lease https://x-access-token:${{ secrets.SCARAB_SYNC_PAT }}@github.com/litz-lab/scarab_ll.git main:pull_${DATE} # Push to pull_<date> branch
